### ISSUE TITLE
Dron uses BFO:0000053 which is neither in RO nor BFO

### ISSUE THREAD

**Issue by matentzn** [mcwdsi/dron#1]
BFO:0000053 (is bearer of) is neither in RO nor BFO. Consider switching to http://purl.obolibrary.org/obo/RO_0000053 (which is probably what was intended in the first place).

**Comment by sjbost** [comment]
Doesn't exist in major BFO release artifacts. Will replace in the future. Would need to update the SQLite database behind the SCALA code.

**Comment by hoganwr** [comment]
Incidentally, I occasionally end up trying to find the BFO artifact that defines BFO_0000053. One reason for that is that I wonder where I got it in the first place. Here it is!

https://raw.githubusercontent.com/BFO-ontology/BFO/refs/heads/master/releases/2014-05-03/owl-group/bfo.owl

It's the temporally-qualified form of "bearer of", specifically "bearer of at some time".
