### ISSUE TITLE
PATO:0000125 not imported in latest dron release

### ISSUE THREAD

**Issue by matentzn** [mcwdsi/dron#44]
<img width="262" alt="image" src="https://github.com/user-attachments/assets/d4320153-64ac-4389-8f3b-0005eafc653a" />

This might lead also to missing inferences

**Comment by hoganwr** [comment]
Thanks! Looks like there is no PATO import configured in dron-odk.yaml. I
think the best solution is to make an import, probably SLME import from
PATO and include that class.
